spring:
  datasource:
    url: jdbc:mysql://localhost:3306/root?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: chenyuxian.cn
    
  redis:
    database: 0
    host: localhost
    password: chenyuxian.cn
    port: 6379
    
#打印sql语句和结果集
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
    
discuz:
  enable-ansi: true
  server-ip: 127.0.0.1