server:
  port: 8083
spring:
  servlet:
    multipart:
      max-request-size: 5120MB
      max-file-size: 5120MB

minio:
  enabled: false
  accessKey: "admin"
  secretKey: "chenyuxian.cn"
  endpoint: "1.15.68.129"
  port: 9000
  
qiniu:
 