server:
  port: 8088
  servlet:
    context-path: /
  undertow:
    max-http-post-size: 0
    buffer-size: 512
    direct-buffers: true
    accesslog:
      dir: D://
      enabled: true
      pattern: common
      prefix: =access_log
      suffix: log

spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    mode: HTML
    suffix: .html
    encoding: UTF-8
    cache: false

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/root?serverTimezone=UTC&useSSL=false
    username: root
    password: chenyuxian.cn
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  mvc:
    favicon:
      enabled: false
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: root@chenyuxian.cn
    password: Qq15777529165
    test-connection: false
    properties:
      from: root@chenyuxian.cn
      mail:
        mime:
          splitlongparameters: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
    